### ISSUE TITLE
Plotting graphs seems to be broken

### ISSUE THREAD

**Issue by woodbri** [woodbri/vehicle-routing-problems#1]
After Converting data to lat-lon the plotting seems to be broken.

**Comment by cvvergara** [comment]
I wouldnt care about it, because we are plotting in the map

**Comment by woodbri** [comment]
Fix or not, but this code also needs to be removed or ifdef'd out before we can integrate it with postgresql. If we are not planning on fixing it, then it should just get removed.

**Comment by cvvergara** [comment]
Once we have the map real map/path in a server, then we can move it aside....  aka, it is usefull speccially when someone  doesn't have a map server in the computer that matches the sample data.... think of future developers solving other TWC problems. 
While we have the server ready, I can try to see where the plot class fails

**Comment by woodbri** [comment]
Thanks for the fix. Closing.
