### ISSUE TITLE
Compilation problems

### ISSUE THREAD

**Issue by fpacheco** [woodbri/vehicle-routing-problems#12]
Dear Stephen:
I have tried to compile the source code (develop branch) with no luck. 

I followed the steps in https://github.com/woodbri/vehicle-routing-problems/tree/develop/src/trash-prob/trashWithMovingDumps/integration.

Actual command line output is:

./make-compile
rm -rf ./bin/trash ./build/*
find . -name "_.d" -type f -delete
find . -name "_.png" -type f -delete
rm -f _.o
rm -f *.so
mkdir -p ./bin
echo initTrash
initTrash
mkdir -p ./build/baseClasses ./build/baseTrash ./build/initTrash ./build/solverTrash ./logs
g++ -g -O0 -MMD  -MP -fPIC  -DOSRMCLIENT -I/disco_local/fpacheco/im/osrm-backend/    -DDOVRPLOG -I/usr/local/include  -DVRPMINTRACE -I../../../baseClasses -I../../baseTrash -I../../initTrash -I../solverTrash -I.  -c ../../../baseClasses/basictypes.cpp -o build/baseClasses/basictypes.o
g++ -g -O0 -MMD  -MP -fPIC  -DOSRMCLIENT -I/disco_local/fpacheco/im/osrm-backend/    -DDOVRPLOG -I/usr/local/include  -DVRPMINTRACE -I../../../baseClasses -I../../baseTrash -I../../initTrash -I../solverTrash -I.  -c ../../../baseClasses/move.cpp -o build/baseClasses/move.o
g++ -g -O0 -MMD  -MP -fPIC  -DOSRMCLIENT -I/disco_local/fpacheco/im/osrm-backend/    -DDOVRPLOG -I/usr/local/include  -DVRPMINTRACE -I../../../baseClasses -I../../baseTrash -I../../initTrash -I../solverTrash -I.  -c ../../../baseClasses/node.cpp -o build/baseClasses/node.o
g++ -g -O0 -MMD  -MP -fPIC  -DOSRMCLIENT -I/disco_local/fpacheco/im/osrm-backend/    -DDOVRPLOG -I/usr/local/include  -DVRPMINTRACE -I../../../baseClasses -I../../baseTrash -I../../initTrash -I../solverTrash -I.  -c ../../../baseClasses/osrmclient.cpp -o build/baseClasses/osrmclient.o
In file included from /usr/include/c++/4.8/unordered_map:35:0,
                 from /usr/local/include/osrm/ServerPaths.h:33,
                 from /disco_local/fpacheco/im/osrm-backend/Library/OSRM.h:31,
                 from ../../../baseClasses/osrmclient.cpp:14:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from ../../../baseClasses/osrmclient.cpp:21:0:
../../../baseClasses/osrmclient.h:20:39: fatal error: DataStructures/Coordinate.h: No existe el archivo o el directorio
 #include "DataStructures/Coordinate.h"
                                       ^
compilation terminated.
make: *_\* [build/baseClasses/osrmclient.o] Error 1
Makefile.library:5: build/vrptools-mk.inc: No existe el archivo o el directorio
Makefile.library:8: **\* Please run make -f Makefile.vrptools.  Alto.
Makefile.library:5: build/vrptools-mk.inc: No existe el archivo o el directorio
Makefile.library:8: **\* Please run make -f Makefile.vrptools.  Alto.

I could not find DataStructures directory in the included directories .

On the other hand ... I must add -std=gnu++11?

Please let me know if I have any way to fix it. Thank You. Best regards. Fernando.

**Comment by fpacheco** [comment]
Sorry I'm NOT using the required version of **osrm-backend**.

When I try to run **git checkout 8f18ba3 -b orsm-tools** git command responds me:
fatal: Cannot update paths and switch to branch 'orsm-tools' at the same time.
Did you intend to checkout '8f18ba3' which can not be resolved as commit?

fatal: Cannot update paths and switch to branch 'orsm-tools' at the same time.
Did you intend to checkout '8f18ba3' which can not be resolved as commit?

Please let me know if I have any way to fix it. Thank You. Best regards. Fernando.

**Comment by woodbri** [comment]
Sorry Looks like that commit is one I did locally to save some stuff I was testing. Can you try with this:

```
git checkout fbbd6ca -b osrm-tools
```

And let me know it that works. Thanks.

**Comment by fpacheco** [comment]
The problem now is:
g++ -g -O0 -MMD  -MP -fPIC  -DOSRMCLIENT -I/disco_local/fpacheco/im/osrm-backend/    -DDOVRPLOG -I/usr/local/include  -DVRPMINTRACE -I../../../baseClasses -I../../baseTrash -I../../initTrash -I../solverTrash -I.  -c trash.cpp -o build/trash.o
trash.cpp: In function ‘int main(int, char**)’:
trash.cpp:67:12: error: ‘IsGoogleLoggingInitialized’ is not a member of ‘google’
   if ( not google::IsGoogleLoggingInitialized() ) {

It's strange because: IsGoogleLoggingInitialized is in src/utilities.h in the library source code, but not in installed headers in /usr/local/glog/ (it's ok?).

Please let me know if I have any way to fix it. Thank You. Best regards. Fernando.

**Comment by cvvergara** [comment]
Fernando, edit the makefile and on line 28 put  a yes to invalidate the trace, also delete the <space>yes on line 52 and on line 57, and see what happens. It should compile without traces, logs and without OSRM.
if it does compiles, you can still test it, it will use euclidean instead of osrm. 
after you make some tests, you can turn on those flags (one by one) and let us know which flag generate your problem.

**Comment by fpacheco** [comment]
Right now I'm in no hurry to testing.  I prefer to solve the compilation of source code with full functionality and then do the testing. I will try to follow the steps you have requested me, then I will send my comments. Thank you.

**Comment by woodbri** [comment]
I just checked on my system and I have:

```
[] /u/software/vrp-google-glog$ grep IsGoogleLoggingInitialized /usr/local/include/glog/*
/usr/local/include/glog/logging.h:GOOGLE_GLOG_DLL_DECL bool IsGoogleLoggingInitialized();
```

Did you build glog from source or install it from a package?
 I installed it from source with `sudo make install`

**Comment by fpacheco** [comment]
I installed glog yesterday, from tar.gz source code (https://google-glog.googlecode.com/files/glog-0.3.3.tar.gz).

fpacheco@igs-010:/usr/local/include/glog$ grep -r . -e IsGoogleLoggingInitialized
fpacheco@igs-010:/usr/local/include/glog$ ls -l
total 92
-rw-r--r-- 1 root root 63945 feb  9 08:05 logging.h
-rw-r--r-- 1 root root  3376 feb  9 08:05 log_severity.h
-rw-r--r-- 1 root root  6937 feb  9 08:05 raw_logging.h
-rw-r--r-- 1 root root  6529 feb  9 08:05 stl_logging.h
-rw-r--r-- 1 root root  6038 feb  9 08:05 vlog_is_on.h

**Comment by woodbri** [comment]
It looks like maybe there is a glog version difference. Here is the tarball that we used:

http://imaptools.com:8080/dl/vrp-google-glog.tgz

You probably should go to your exiting src directory for glog and do `sudo make uninstall` and then build and install the one from our tarball. I'll open a ticket to track this.

**Comment by fpacheco** [comment]
Others problems(??):
-  I have some libs in /lib/x86_64-linux-gnu. This directory is not in the search path for libraries (-L). Can not find -lgd ... I add the directory to Makefile (-L/lib/x86_64-linux-gnu). Works fine;
- line 134:  **/usr/bin/ld: no se puede encontrar -lUUID** ¿May be libuuid? ¿Must be -luuid?
- line 134: **/usr/bin/ld: no se puede encontrar -lGITDESCRIPTION** I have no idea. Did you?. 

Please let me know if I have any way to fix it. Thank You. Best regards. Fernando.

**Comment by woodbri** [comment]
These issues are related to how osrm-backend was built and installed. It was a long time ago and I probably forgot some steps. But here is what I think I did.

When I complied and link osrm-backend, I copy and pasted the libraries used on the link command to this the variable:

```
OSRMCLIENT_LIBS = -L/usr/local/lib -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lOSRM -lUUID -lGITDESCRIPTION -lz -lrt -lboost_filesystem -lboost_iostreams -lboost_program_options -lboost_regex -lboost_system -lboost_thread -lpthread -lstxxl
```

I don't think osrm-backend has a make install target so what I did was copy files something like this:

```
cd /path/to/osrm-backend/build
sudo cp libGITDESCRIPTION.a libUUID.a libOSRM.so /usr/local/lib/.
```

This should resolve these issues. Thank you for your patience, these issues will help us make better documentation.

**Comment by fpacheco** [comment]
Solved. Thank you. Fernando.
