### ISSUE TITLE
Update html map to support multiple Path

### ISSUE THREAD

**Issue by woodbri** [woodbri/vehicle-routing-problems#4]
need to update getTrash.php to extract multiple paths
need to update HTML to color each path

**Comment by cvvergara** [comment]
Eventually it would be nice to have a setup for a small sample data. just as we are doing, so that developers can veiw in their own mapserver installation the generated paths.

**Comment by woodbri** [comment]
I think that when we get to that point, maybe we can enlist Daniel to make a nice demo ;)

**Comment by woodbri** [comment]
http://imaptools.com:8080/demo/montevideo.html
Fixed. closing.
