### ISSUE TITLE
Create a Config singleton that can hold application level options

### ISSUE THREAD

**Issue by woodbri** [woodbri/vehicle-routing-problems#6]
I added a baseClasses/singleton.h and baseTrash/trashconfig.h this needs to be tested and integrated. I currently have:

```
CONFIG->osrmBaseUrl
CONFIG->plotDir
CONFIG->plotFontFile
```

defined as public and initialized, but these can be overwritten as need. The relevant code needs to be updated to use these variables.

**Comment by woodbri** [comment]
This needs to be documented. It is currently used in:

```
./baseTrash/trashconfig.h
./baseTrash/vehicle.cpp
./trash-prob/sdev-trash/trash.cpp
```

**Comment by cvvergara** [comment]
pgrouting uses cmake, and this will be integrated to pgrouting, my Q is: what is the impact of changing the way this is configured to be different of the other pgrouting functions?

**Comment by woodbri** [comment]
pgrouting has no configuration options today that I can think of. The code is very simplistic and atomic in general, if there are configuration parameters, they are passed to the code via the SQL, In the main wrapper function we can take those passed arguments and set them in the Config object and then our code will use them appropriately. I don't see any issues.
